#!/bin/bash

BASEDIR="$(dirname "${BASH_SOURCE[0]}")"

( source "$BASEDIR/templates/update_dskey" ) | sed 's/<password>.*<\/password>/<password>HIDDEN<\/password>/'
echo ""
echo "==================================="
echo ""
( source "$BASEDIR/templates/update_dskey" ) | "$BASEDIR/call_api.py" 2>&1

exit 0 