#!/bin/bash

if [ ! -v CONFIG ]; then
	CONFIG="/etc/simple-dnssec/common.conf"
fi

if [ ! -f $CONFIG ]; then
	echo "Config file does not exist. Please install this application."
	exit 1
fi

source $CONFIG

if [ ! -v PREFIX ]; then
	PREFIX=$(readlink -f "$(dirname $(readlink -f "$0"))/../../")
fi

if [ -z "$1" ]; then
	mkdir -p "$BASEDIR/dskeys"
	file="$BASEDIR/dskeys/dskey.$(date +%Y%m%d%H%M%S)"
	cat > $file
	cat $file | mail -s"Please refresh your DS-record(s)" $MAILADDRESS
else
	file="$1"
fi

declare -a FLAGS
declare -a PROTOCOLS
declare -a ALGORITHMS
declare -a KEYS
while read entry; do
	ZONE=$(echo "$entry" | awk '{print $1}')
	[ "X${ZONE:(-1)}" = "X." ] && ZONE="${ZONE%\.}"
	KEYTAG=$($PREFIX/share/simple-dnssec/gen_keytag $(echo "$entry" | awk '{printf "%s %s %s %s", $5, $6, $7, $8}'))
	echo "0 *     * * *     root   $PREFIX/share/simple-dnssec/ds_seen $ZONE $KEYTAG $file" > /etc/cron.d/waitfords-$KEYTAG
	
	FLAGS+=($(echo "$entry" | awk '{print $5}'))
	PROTOCOLS+=($(echo "$entry" | awk '{print $6}'))
	ALGORITHMS+=($(echo "$entry" | awk '{print $7}'))
	KEYS+=($(echo "$entry" | awk '{print $8}'))
done < "$file"

(
	if [ -d "$PREFIX/share/simple-dnssec/providers/$PROVIDER" ]; then
		source "$PREFIX/share/simple-dnssec/providers/$PROVIDER/update_ds"
	else
		echo "PLEASE ADD SUPPORT FOR YOU PROVIDER'S DNS API FIRST."
	fi
) | mail -a "From: $MAILSENDER" -s "DS-record update requested for $ZONE" $MAILRECIPIENT

#also update nameservers to be on the safe side
DOMAIN="$ZONE"
(
	if [ -d "$PREFIX/share/simple-dnssec/providers/$PROVIDER" ]; then
		source "$PREFIX/share/simple-dnssec/providers/$PROVIDER/update_ns"
	else
		echo "PLEASE ADD SUPPORT FOR YOU PROVIDER'S DNS API FIRST."
	fi
) | mail -a "From: $MAILSENDER" -s "Nameserver update requested for $DOMAIN" $MAILRECIPIENT
echo "$newnshash" > $BASEDIR/${DOMAIN}.d/nameservers.hash

exit 0