#!/bin/bash

set -euo pipefail
IFS=$'\n\t'

if [ ! -v CONFIG ]; then
    CONFIG="/etc/simple-dnssec/common.conf"
fi

if [ ! -f $CONFIG ]; then
    echo "Config file does not exist. Please install this application."
    exit 1
fi

source $CONFIG

if [ ! -v PREFIX ]; then
    PREFIX=$(readlink -f "$(dirname $(readlink -f $0))/../")
fi

source $PREFIX/share/simple-dnssec/common.sh

for zonefile in /var/lib/opendnssec/signed/*; do
    ZONE="$(basename $zonefile)"
    source $PREFIX/share/simple-dnssec/templates/bind_zone_template
done > /etc/bind/named.conf.simple-dnssec
rndc reload
rndc flush
exit 0
