#!/bin/bash
for i in /var/lib/opendnssec/signed/*; do
	ZONE="$(basename $i)"
	source /usr/local/share/simple-dnssec/templates/nsd_zone_template
done > /etc/nsd/nsd.conf.d/zones.conf
nsd-control reconfig
sleep 1
nsd-control reload
exit 0
